spring:
  datasource:
    url: jdbc:h2:mem:booking-service
    driverClassName: org.h2.Driver
    username: booking-service-app
    password: booking-service-password
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true